### ISSUE TITLE
unable to decompress shared windows exe file

### ISSUE THREAD

**Issue by nav60** [misaka00251/llvm-windows-x64#2]
Hi,
Thanks for sharing LLVM package for windows. However winrar and 7z is not decompressing it. please check it if you can verify it

**Comment by misaka00251** [comment]
I'm sorry, can you try [7-Zip-zstd](https://github.com/mcmilk/7-Zip-zstd)?

**Comment by misaka00251** [comment]
This should be fixed in the newest release as the installer is back.
