### ISSUE TITLE
May I ask the steps to build this project?

### ISSUE THREAD

**Issue by ouliuquan** [misaka00251/llvm-windows-x64#3]
Hello, I am using your Windows installation package, and then I found that the Clang compiler version on Visual Studio 2022 17.6.2 is 15.0.1, and some code compilation and link requirements are exactly the same (maybe there is a problem with my code ), did not find this version, I want to compile a copy according to your compilation method, or you can help compile and release this version, can you? thank you very much for your help.

你好，我在实用你的这个Windows安装包，然后我发现Visual Studio 2022 17.6.2上的Clang编译器版本是15.0.1，有的代码编译链接要求完全一样（也可能是我的代码有问题），找了没有发现这个版本，想根据你的编译方法编译一份，或者你帮忙编译发布这个版本，可以吗？非常感谢你的帮助。

**Comment by ouliuquan** [comment]
Your compiled version is the most complete, including some libs that are not in the [official ](https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.1)installation package, so I want to get your help to release a version 15.0.1 corresponding to VS.

你的这个编译版本是最全的，包含了一些官方安装包都没有的lib，所以我这边想得到你的帮助，发布一个跟VS 对应的15.0.1版本。

**Comment by misaka00251** [comment]
I'm lazy so I build my releases using [clangbuilder](https://github.com/fstudio/clangbuilder). You can edit the `config/llvm.json` to specify the version you want.
